/*
-----------------------------------------------------------------------------
Filename:    ogremagix.cpp
-----------------------------------------------------------------------------

This source file is generated by the Ogre AppWizard.

Check out: http://conglomerate.berlios.de/wiki/doku.php?id=ogrewizards

Based on the Example Framework for OGRE
(Object-oriented Graphics Rendering Engine)

Copyright (c) 2000-2007 The OGRE Team
For the latest info, see http://www.ogre3d.org/

You may use this sample code for anything you like, it is not covered by the
LGPL like the rest of the OGRE engine.
-----------------------------------------------------------------------------
*/

#include "ogremagixApp.h"
#include <fstream>
#include <string>
#include <iostream>

#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#define WIN32_LEAN_AND_MEAN
#include "windows.h"
#include <tlhelp32.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

	// Функция проверки запуска через лаунчер
	bool checkLauncher() {
		std::ifstream file("launcher.tmp");
		if (file.is_open()) {
			file.close();
			// Удаляем временный файл
			remove("launcher.tmp");
			return true;
		}
		return false;
	}

	// Функция проверки, запущена ли уже игра
	bool isGameAlreadyRunning() {
		// ЗАКОММЕНТИРОВАНО: временно отключаем проверку на уже запущенную игру
		return false;
		/*
		#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
		// Получаем имя текущего процесса
		char currentProcessName[MAX_PATH];
		GetModuleFileNameA(NULL, currentProcessName, MAX_PATH);
		std::string currentExe = currentProcessName;
		currentExe = currentExe.substr(currentExe.find_last_of("\\") + 1);

		// Создаем снимок всех процессов
		HANDLE hSnapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
		if (hSnapshot == INVALID_HANDLE_VALUE) {
		return false;
		}

		PROCESSENTRY32 pe32;
		pe32.dwSize = sizeof(PROCESSENTRY32);

		int processCount = 0;

		if (Process32First(hSnapshot, &pe32)) {
		do {
		std::string processName = pe32.szExeFile;
		if (processName == currentExe) {
		processCount++;
		// Если нашли более одного процесса с таким именем, значит игра уже запущена
		if (processCount > 1) {
		CloseHandle(hSnapshot);
		return true;
		}
		}
		} while (Process32Next(hSnapshot, &pe32));
		}

		CloseHandle(hSnapshot);
		return false;
		#else
		// Для Linux/Unix можно использовать проверку через файл .pid
		// или другие методы, но для простоты возвращаем false
		return false;
		#endif
		*/
	}

	// Функция показа сообщения об ошибке запуска через лаунчер
	void showLauncherErrorMessage() {
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
		MessageBoxA(NULL,
			"Запускайте игру через launcher.exe!\n\nПожалуйста, используйте лаунчер для запуска игры.",
			"Ошибка запуска",
			MB_OK | MB_ICONERROR | MB_TASKMODAL);
#else
		std::cout << "=====================================" << std::endl;
		std::cout << "         ОШИБКА ЗАПУСКА" << std::endl;
		std::cout << "=====================================" << std::endl;
		std::cout << std::endl;
		std::cout << "Запускайте игру через launcher!" << std::endl;
		std::cout << std::endl;
		std::cout << "Нажмите Enter для выхода...";
		std::cin.get();
#endif
	}

	// Функция показа сообщения об уже запущенной игре
	void showAlreadyRunningErrorMessage() {
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
		MessageBoxA(NULL,
			"Игра уже запущена!\n\nПожалуйста, закройте предыдущую копию игры перед запуском новой.",
			"Игра уже запущена",
			MB_OK | MB_ICONWARNING | MB_TASKMODAL);
#else
		std::cout << "=====================================" << std::endl;
		std::cout << "    ИГРА УЖЕ ЗАПУЩЕНА" << std::endl;
		std::cout << "=====================================" << std::endl;
		std::cout << std::endl;
		std::cout << "Пожалуйста, закройте предыдущую копию игры!" << std::endl;
		std::cout << std::endl;
		std::cout << "Нажмите Enter для выхода...";
		std::cin.get();
#endif
	}

#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
	INT WINAPI WinMain(HINSTANCE hInst, HINSTANCE, LPSTR strCmdLine, INT)
#else
	int main(int argc, char *argv[])
#endif
	{
		// Проверяем, что игра запущена через лаунчер
		if (!checkLauncher()) {
			showLauncherErrorMessage();
			return 1;
		}

		// Проверяем, не запущена ли игра уже
		// ЗАКОММЕНТИРОВАНО: временно отключаем проверку на уже запущенную игру
		/*
		if (isGameAlreadyRunning()) {
		showAlreadyRunningErrorMessage();
		return 2;
		}
		*/

		// Create application object
		ogremagixApp app;
		//MagixMain app;

		try {
			app.go();
		}
		catch (Ogre::Exception& e) {
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
			MessageBoxA(NULL, e.getFullDescription().c_str(), "An exception has occured!", MB_OK | MB_ICONERROR | MB_TASKMODAL);
#else
			std::cerr << "An exception has occured: " <<
				e.getFullDescription().c_str() << std::endl;
#endif
		}

		return 0;
	}

#ifdef __cplusplus
}
#endif